version: '3'
services:
  app:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-12-may-2020/group-projects/sagittarius/luna_project:latest
    env_file:
      - ./env/dev.env
    ports:
      - '8000:8000'
    volumes:
    - ./backend:/backend
    command: "python manage.py runserver 0:8000"
    depends_on:
      - db

  db:
    image: postgres:11
    env_file:
      - ./env/dev.env
    ports:
    - '5432:5432'

volumes:
    postgres_db: